import { Campaign, Promotion } from "@/types";

export const headerColor = "#324B51";
export const navBarColor = "#456770";
export const bgColor = "#AAAAAA";
export const unKnownColor = "#494949";
export const pageBgColor = "#E9ECF0";
export const primaryColor = "#4D7C8A";

export const status = {
  active: "#1FB544",
  pending: "#EB9F13",
  stop: "#E64141",
};

export const card = {
  background: "#F3F3F3",
  border: "#E8E8E8",
};

export const tabs = [
  "Advertisement Dashboard",
  "Banner Setup Page",
  "Promotion",
];

export const campaigns: Campaign[] = [
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "1 - 20%",
    history: "Review",
    status: "active",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "1 - 20%",
    history: "Review",
    status: "active",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "1 - 20%",
    history: "Review",
    status: "active",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "1 - 20%",
    history: "Review",
    status: "pending",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "n/a",
    history: "Review",
    status: "stop",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "n/a",
    history: "Review",
    status: "stop",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "n/a",
    history: "Review",
    status: "pending",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "n/a",
    history: "Review",
    status: "pending",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "n/a",
    history: "Review",
    status: "stop",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "n/a",
    history: "Review",
    status: "stop",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "n/a",
    history: "Review",
    status: "pending",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "n/a",
    history: "Review",
    status: "pending",
  },
  {
    name: "Companyname:ID001p5",
    id: "123456",
    type: "H1",
    maturity: "09-15-2025",
    impressions: 1200,
    clicks: 45,
    length: "1 month",
    saleValue: "$500",
    discount: "1 - 20%",
    history: "Review",
    status: "active",
  },
];

export const promotions: Promotion[] = [
  {
    name: "Company A",
    type: "1",
    impressions: 1200,
    clicks: 34,
    shares: 89,
    conversions: 67,
    length: "1 month",
    details: "Promotion link",
    promotion: "Promotion Name",
  },
  {
    name: "Company A",
    type: "1",
    impressions: 1200,
    clicks: 34,
    shares: 89,
    conversions: 67,
    length: "1 month",
    details: "Promotion link",
    promotion: "Promotion Name",
  },
  {
    name: "Company A",
    type: "1",
    impressions: 1200,
    clicks: 34,
    shares: 89,
    conversions: 67,
    length: "1 month",
    details: "Promotion link",
    promotion: "Promotion Name",
  },
  {
    name: "Company A",
    type: "1",
    impressions: 1200,
    clicks: 34,
    shares: 89,
    conversions: 67,
    length: "1 month",
    details: "Promotion link",
    promotion: "Promotion Name",
  },
];

export const durations = [
  "3 Days",
  "1 Week",
  "2 Weeks",
  "1 Month",
  "2 Months",
  "3 Months",
  "6 Months",
  "1 Year",
];

export const data = [
  {
    headerType: "H1",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "H2",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "H3",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "H4",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "H5",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "H6",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "H7",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "H1",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "E1",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "E2",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "E3",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "E4",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "E5",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
  {
    headerType: "E3",
    rows: [
      {
        label: "Minimum percentage deposit",
        values: [
          "100%",
          "100%",
          "100%",
          "100%",
          "monthly",
          "monthly",
          "monthly",
          "monthly",
        ],
      },
      {
        label: "Volume discount",
        values: [
          "",
          "",
          "",
          "",
          "95% of min % deposit",
          "95% of min % deposit",
          "87% of min % deposit",
          "84% of min % deposit",
        ],
      },
      {
        label: "Payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$300 × 2",
          "$280 × 3",
          "$270 × 6",
          "$250 × 12",
        ],
      },
      {
        label: "1 time payment",
        values: [
          "$70",
          "$100",
          "$180",
          "$320",
          "$570",
          "$750",
          "$1400",
          "$2500",
        ],
      },
      {
        label: "Additional info",
        values: [
          "Basic",
          "Standard",
          "Standard",
          "Premium",
          "Premium",
          "Premium",
          "Enterprise",
          "Enterprise",
        ],
      },
    ],
  },
];
